config/routes.rb
OrderForm::Application.routes.draw do

  get "static_pages/home"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :products, only: [:create, :destroy]

  root to: 'static_pages#home'
  
  match '/register', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :billing_frequency
  
  # this product belongs to a user
  belongs_to :user

  # make sure that user id isn't blank
  validates :user_id, presence: true

  # make sure that name isn't blank and its maximum length is 100 characters
  validates :name, presence: true, length: { maximum: 100 }

  # make sure that billing frequency isn't blank
  validates :billing_frequency, presence: true

  # arrange in descending order from newest to oldest
  default_scope order: 'products.created_at DESC'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  has_many :products, dependent: :destroy

  # make sure that emails are downcased before being saved to the db
  before_save { self.email.downcase! }

  # create remember token
  before_save :create_remember_token

  # make sure that name is non-blank and is a maximum of 50 characters
  validates :name, presence: true, length: { maximum: 50 }

  # make sure that email is non-blank and is a valid email address,
  # ignoring case
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
		    uniqueness: { case_sensitive: false }
  # make sure that password is non-blank and is at least 6 characters long
  validates :password, presence: true, length: { minimum: 6 }

  # make sure that password confirmation is non-blank
  validates :password_confirmation, presence: true

  def display
    # This is preliminary.
    Product.where("user_id = ?", id)
  end

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy]
  before_filter :correct_user, only: :destroy

  def create
    @product = current_user.products.build(params[:product])
    if @product.save
      flash[:success] = "Product created!"
      redirect_to root_path
    else
      @display_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @product.destroy
    redirect_to root_path
  end

  private

    def correct_user
      @product = current_user.products.find_by_id(params[:id])
      redirect_to root_path if @product.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or root_path
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @product = current_user.products.build
      @display_items = current_user.display.paginate(page: params[:page])
    end
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :signed_in_user, only: [:show, :edit, :update, :destroy]
  before_filter :correct_user, only: [:show, :edit, :update]
  before_filter :admin_user, only: [:index, :destroy]
  
  def show
    @user = User.find(params[:id])
  end  

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      
      # send a welcome email
      UserMailer.welcome_email(@user).deliver

      sign_in @user
      flash[:success] = "Welcome to Order Form!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @products = @user.products.paginate(page: params[:page])
  end

  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless (current_user?(@user) || current_user.admin?)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Order Form"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in."
    end
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.fullpath
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    written by <a href="http://www.levion.com/">Levion, LLC</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", 'mailto:niko@levion.com' %></li>
    </ul>
  </nav> 
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Order Form", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
            <% if current_user.admin? %>
              <li><%= link_to "Users", users_path %></li>
            <% end %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Update profile", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/products/_product.html.erb
<li>
  <span class="name"><%= product.name %></span>
  <span class="billing_frequency"><%= product.billing_frequency %></span>
  <span class="timestamp">
    added <%= time_ago_in_words(product.created_at) %> ago.
  </span>
  <% if current_user?(product.user) %>
    <%= link_to "delete", product, method: :delete,
				   data: { confirm: "You sure?" },
				   title: product.name + " | " + product.billing_frequency %>
  <% end %>
</li>

app/views/shared/_display.html.erb
<% if @display_items.any? %>
  <ol class="products">
    <%= render partial: 'shared/display_item', collection: @display_items %>
  </ol>
  <%= will_paginate @display_items %>
<% end %>

app/views/shared/_display_item.html.erb
<li id="<%= display_item.id %>">
  <%= link_to gravatar_for(display_item.user), display_item.user %>
  <span class="user">
    <%= link_to display_item.user.name, display_item.user %>
  </span>
  <span class="name"><%= display_item.name %></span>
  <span class="billing_frequency"><%= display_item.billing_frequency %></span>
  <span class="timestamp">
    Added <%= time_ago_in_words(display_item.created_at) %> ago.
  </span>
  <% if current_user?(display_item.user) %>
    <%= link_to "delete", display_item, method: :delete,
					data: { confirm: "You sure?" },
					title: display_item.name + " | " + display_item.billing_frequency %>
  <% end %>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_product_form.html.erb
<%= form_for(@product) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :billing_frequency %>
    <%= f.text_field :billing_frequency %>
  </div>
  <%= f.submit "Add product", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= gravatar_for current_user, size: 52 %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= pluralize(current_user.products.count, "product") %>
</span>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/product_form' %>
      </section>
    </aside>
    <div class="span8">
      <h3>Product Display</h3>
      <%= render 'shared/display' %>
    </div>
  </div>
<% else %>
  <div class="center hero-unit">
    <h1>Welcome to Order Form!</h1>

    <h2>
      Manage product orders from anywhere.
    </h2>

    <%= link_to "Sign up now!", register_path, class: "btn btn-large btn-primary" %>
    <%= link_to "Log in as existing user", signin_path, class: "btn btn-large btn-primary" %>
  </div>

  <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
<% end %>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
				  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Register') %>
<h1>Register as New User</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="span8">
    <% if @user.products.any? %>
      <h3>Products (<%= @user.products.count %>)</h3>
      <ol class="products">
        <%= render @products %>
      </ol>
      <%= will_paginate @products %>
    <% end %>
  </div>
</div>